spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  application:
    name: ite-3rd-ecommerce
server:
  port: 9990
